// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Accidental$BsMusicTheory = require("../src/Accidental.bs.js");

Jest.testAll("accidentals", /* :: */[
      /* tuple */[
        Accidental$BsMusicTheory.multiplyInt(Accidental$BsMusicTheory.flat, 2),
        Accidental$BsMusicTheory.doubleFlat
      ],
      /* :: */[
        /* tuple */[
          Accidental$BsMusicTheory.divideInt(Accidental$BsMusicTheory.doubleFlat, 2),
          Accidental$BsMusicTheory.flat
        ],
        /* :: */[
          /* tuple */[
            Accidental$BsMusicTheory.subtractInt(Accidental$BsMusicTheory.sharps(2), 2),
            Accidental$BsMusicTheory.natural
          ],
          /* :: */[
            /* tuple */[
              Accidental$BsMusicTheory.addInt(Accidental$BsMusicTheory.flats(2), 2),
              Accidental$BsMusicTheory.natural
            ],
            /* :: */[
              /* tuple */[
                Accidental$BsMusicTheory.add(Accidental$BsMusicTheory.sharps(2), Accidental$BsMusicTheory.sharps(1)),
                Accidental$BsMusicTheory.makeWithInteger(3)
              ],
              /* [] */0
            ]
          ]
        ]
      ]
    ], (function (param) {
        var match = Caml_obj.caml_equal(param[0], param[1]);
        if (match) {
          return Jest.pass;
        } else {
          return Jest.fail("");
        }
      }));

Jest.testAll("make with string literal", /* :: */[
      /* tuple */[
        Accidental$BsMusicTheory.makeWithString("#"),
        /* Sharps */Block.__(1, [1])
      ],
      /* :: */[
        /* tuple */[
          Accidental$BsMusicTheory.makeWithString("##"),
          /* Sharps */Block.__(1, [2])
        ],
        /* :: */[
          /* tuple */[
            Accidental$BsMusicTheory.makeWithString("###"),
            /* Sharps */Block.__(1, [3])
          ],
          /* :: */[
            /* tuple */[
              Accidental$BsMusicTheory.makeWithString("b"),
              /* Flats */Block.__(0, [1])
            ],
            /* :: */[
              /* tuple */[
                Accidental$BsMusicTheory.makeWithString("bb"),
                /* Flats */Block.__(0, [2])
              ],
              /* :: */[
                /* tuple */[
                  Accidental$BsMusicTheory.makeWithString("bbb"),
                  /* Flats */Block.__(0, [3])
                ],
                /* :: */[
                  /* tuple */[
                    Accidental$BsMusicTheory.makeWithString(""),
                    /* Natural */0
                  ],
                  /* :: */[
                    /* tuple */[
                      Accidental$BsMusicTheory.makeWithString("#b#b"),
                      /* Natural */0
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ], (function (param) {
        return Jest.Expect[/* toEqual */12](param[1], Jest.Expect[/* expect */0](param[0]));
      }));

/*  Not a pure module */
