// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Interval$BsMusicTheory = require("../src/Interval.bs.js");
var ChordType$BsMusicTheory = require("../src/ChordType.bs.js");

Jest.test("sanity", (function (param) {
        var actual = ChordType$BsMusicTheory.ChordThirdType[/* makeWithInterval */0](Interval$BsMusicTheory.major3);
        return Jest.Expect[/* toBe */2](/* Major */0, Jest.Expect[/* expect */0](actual));
      }));

/*  Not a pure module */
