// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var KeyType$BsMusicTheory = require("../src/KeyType.bs.js");

Jest.testAll("atDistance", /* :: */[
      /* tuple */[
        /* D */1,
        -2,
        /* B */6
      ],
      /* :: */[
        /* tuple */[
          /* D */1,
          -19,
          /* F */3
        ],
        /* :: */[
          /* tuple */[
            /* D */1,
            12,
            /* B */6
          ],
          /* :: */[
            /* tuple */[
              /* D */1,
              0,
              /* D */1
            ],
            /* :: */[
              /* tuple */[
                /* D */1,
                1,
                /* E */2
              ],
              /* :: */[
                /* tuple */[
                  /* D */1,
                  2,
                  /* F */3
                ],
                /* :: */[
                  /* tuple */[
                    /* D */1,
                    -3,
                    /* A */5
                  ],
                  /* :: */[
                    /* tuple */[
                      /* D */1,
                      -301,
                      /* D */1
                    ],
                    /* :: */[
                      /* tuple */[
                        /* F */3,
                        -3,
                        /* C */0
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ], (function (param) {
        var match = KeyType$BsMusicTheory.key(param[0], param[1]) === param[2];
        if (match) {
          return Jest.pass;
        } else {
          return Jest.fail("");
        }
      }));

Jest.testAll("distanceFrom", /* :: */[
      /* tuple */[
        /* D */1,
        /* B */6,
        5
      ],
      /* :: */[
        /* tuple */[
          /* D */1,
          /* F */3,
          2
        ],
        /* :: */[
          /* tuple */[
            /* D */1,
            /* D */1,
            0
          ],
          /* :: */[
            /* tuple */[
              /* D */1,
              /* E */2,
              1
            ],
            /* :: */[
              /* tuple */[
                /* D */1,
                /* F */3,
                2
              ],
              /* :: */[
                /* tuple */[
                  /* D */1,
                  /* A */5,
                  4
                ],
                /* :: */[
                  /* tuple */[
                    /* F */3,
                    /* C */0,
                    -3
                  ],
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ], (function (param) {
        var match = KeyType$BsMusicTheory.distance(param[0], param[1]) === param[2];
        if (match) {
          return Jest.pass;
        } else {
          return Jest.fail("");
        }
      }));

/*  Not a pure module */
